export class Customer {
title:String|undefined
firstName:String|undefined
middleName:String|undefined
lastName:String|undefined
fatherName:String|undefined
mobileNum:Number|undefined
emailID:String|undefined
aadharNum:String|undefined
dob:Date|undefined
rAddrLine1:String|undefined
rAddrLine2:String|undefined
rLandmark:String|undefined
rState:String|undefined
rCity:String|undefined
rPincode:String|undefined
mAddrLine1:String|undefined
mAddrLine2:String|undefined
mLandmark:String|undefined
mState:String|undefined
mCity:String|undefined
mPincode:String|undefined
occType:String|undefined
sourceOfIncome:String|undefined
grossAnnualIncome:Number|undefined
debitCard:String|undefined
netBanking:String|undefined
balance:String|undefined
isApproved:String|undefined
}
